units:
  wraps:
  - name: PrometheusxApixClientGitHubURLWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-api-client
    run:
      justification:
      - type: INFO
        message: Package 'prometheus-api-client' is hosted on GitHub
        link: https://github.com/4n4nd/prometheus-api-client-python
        package_name: prometheus-api-client
