units:
  wraps:
  - name: PrometheusxApixClientGitHubReleaseNotesWrap
    type: wrap.GHReleaseNotes
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-api-client
    run:
      release_notes:
        organization: AICoE
        repository: prometheus-api-client-python
        tag_version_prefix: v
