units:
  wraps:
  - name: PrometheusxApixClientPyPIProjectMaintainersWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-api-client
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: WARNING
        message: Project 'prometheus-api-client' has low number of maintainers on PyPI (less than 3)
        link: https://pypi.org/project/prometheus-api-client/
        package_name: prometheus-api-client
