units:
  wraps:
  - name: PrometheusFlaskExporterPyPIProjectMaintainersWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-flask-exporter
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: WARNING
        message: Project 'prometheus-flask-exporter' has low number of maintainers on PyPI (less than 3)
        link: https://pypi.org/project/prometheus-flask-exporter/
        package_name: prometheus-flask-exporter
