units:
  wraps:
  - name: PrometheusClientPyPIMaintainerProjectsWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-client
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: WARNING
        message: >-
          Project 'prometheus-client' is maintained by maintainers that maintain small
          number of projects on PyPI (less than 3)
        link: https://pypi.org/project/prometheus-client/
        package_name: prometheus-client
